### ISSUE TITLE
Add function for "on load"

### ISSUE THREAD

**Issue by dsmithni** [NISystemsEngineering/CEF#64]
Let nodes refresh themselves when they load. This would be the equivalent of initialize for nodes which have already been initialized, probably called during read file or write tree.

Not sure if this has a use case any different from #65

**Comment by becega** [comment]
If the UI has a refresh case just calling this refreshes the node. Do we really need another place to do it?
 I like how we are doing it on the advance version it should be enough.

**Comment by dsmithni** [comment]
What happens if the UI never gets loaded. This had happened many many many many times with platy. For example right now if you delete channels from a fixed channel module you have to go to the UI to fix it. If you don't you get a runtime error. You also have to go to the engine in some cases. Additionally the engine has to do a ton of extra work in the refresh case which is unrelated to refreshing the ui

**Comment by becega** [comment]
Ok that makes sense is a place to update the configuration class of the nodes. 
But then more than letting the nodes themselves is having a place to refresh offline nodes.
This only affects nodes with dependencies like tags from other nodes. So I could be an optional override.

**Comment by dsmithni** [comment]
yes, all these are optional overrides.

and yes this particular one would be for nodes which are never touched. In fact it might be better to unify these into a single function 'refresh it all' which could be called whenever we switch UIs. That way nodes can respond to changes in other nodes.
