### ISSUE TITLE
add function for "pre-run"

### ISSUE THREAD

**Issue by dsmithni** [NISystemsEngineering/CEF#65]
Another bookkeeping operation to be called just before running the UI for a node. Currently there is usually some code which has to be called once to make sure the node is in a good state, but the node has to do it in the uI because there is no other race-free location. This would be that race-free location.

**Comment by becega** [comment]
What type of operations besides refresh are you planning to have?

**Comment by dsmithni** [comment]
None that I know of. But there is a ton of code in place for ' what happened while I was asleep' and this would let us put the code in one place and not clutter the ui
